name: firebase_cloud_messaging_backend
description: Use Firebase Cloud Messaging in your dart server code
author: lotrofans
version: 1.0.1
homepage: https://github.com/lotrofans/firebase_cloud_messaging_backend_dart
# homepage: https://www.example.com
# author: Simon <simon@pdad.de>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  json_serializable: ^3.2.2
  json_annotation: ^3.0.0
  googleapis_auth: ^0.2.10

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: ^1.7.1

